name: overload
description: "A gym app"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.5.1
  logger: ^2.4.0
  get_it: ^8.0.3
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  event_bus: ^2.0.1
  iconify_flutter: ^0.0.7
  animated_custom_dropdown: ^3.1.1
  number_selector: ^1.0.7
  data_table_2: ^2.5.18
  pluto_grid: ^8.0.0
  intl: ^0.19.0
  timelines_plus: ^1.0.6
  timeago: ^3.7.0
  introduction_screen: ^3.1.16
  confetti: ^0.8.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.3
  faker: ^2.2.0


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
